- name: Add ignore vagrant-libvirt to DNF config
  become: true
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: "^exclude="
    line: "exclude=vagrant-libvirt"

- name: Add Hashicorp repository
  become: true
  ansible.builtin.yum_repository:
    name: hashicorp
    description: Hashicorp repository
    baseurl: "{{ _vagrant_baseurl }}"
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    enabled: true

- name: Install Vagrant
  become: true
  ansible.builtin.yum:
    name:
      - vagrant
      - guestfs-tools
      - ruby-libs
      - rubygem-fog-libvirt
      - rubygem-nokogiri
      - rubygem-rexml
      - rubygems
    state: present
